version: "3"

services:
  nodered:
    image: nodered/node-red:latest
    environment:
        - TZ=America/New_York
    ports: 
        - "1880:1880"
    volumes:
        - node-red-data:/data
volumes:
  node-red-data:
